eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@192.168.56.122:8761/eureka/
      
server:
  port: 8763
  
spring:
  application:
    name: eshop-price-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.56.120:3306/eshop
    username: root
    password: root